on: [push]
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    
    - uses: actions/checkout@master
    
    - uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Create ACR
      id: create-acr
      run: |
        az acr create -n halpur -g halpurbeb2-rg --location "North Europe" --sku Basic --admin-enabled
        echo "::set-output name=acr_username::`az acr credential show -n halpur --query username | xargs`"
        echo "::set-output name=acr_password::`az acr credential show -n halpur --query passwords[0].value | xargs`"
        echo "::add-mask::`az acr credential show -n halpur --query passwords[0].value | xargs`"

    - uses: azure/docker-login@v1
      with:
        login-server: halpur.azurecr.io
        username: ${{ steps.create-acr.outputs.acr_username }}
        password: ${{ steps.create-acr.outputs.acr_password }}

    - name: Build and push image to ACR
      id: build-image
      run: |
        docker build "$GITHUB_WORKSPACE/" -f  "Dockerfile" -t halpur.azurecr.io/helloworldaks:${{ github.sha }} --label dockerfile-path=Dockerfile
        docker push halpur.azurecr.io/helloworldaks:${{ github.sha }}
    
    - uses: azure/k8s-set-context@v1
      id: login
      with:
         kubeconfig: ${{ secrets.aks_helloworldaks_kubeConfig }}
    
    - name: Create namespace
      run: |
        namespacePresent=`kubectl get namespace | grep helloworld-ns | wc -l`
        if [ $namespacePresent -eq 0 ]
        then
            echo `kubectl create namespace helloworld-ns`
        fi

    - uses: azure/k8s-create-secret@v1
      with:
        namespace: helloworld-ns
        container-registry-url: halpur.azurecr.io
        container-registry-username: ${{ steps.create-acr.outputs.acr_username }}
        container-registry-password: ${{ steps.create-acr.outputs.acr_password }}
        secret-name: helloworldakdockerauth
       
    - uses: azure/k8s-deploy@v1.2
      with:
        namespace: helloworld-ns
        manifests: |
          manifests/deployment.yml
          manifests/service.yml
          manifests/ingress.yml
        images: |
          halpur.azurecr.io/helloworldaks:${{ github.sha }}
        imagepullsecrets: |
          helloworldakdockerauth   
